### ISSUE TITLE
investigate and fix correlation id was not found

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/interactsh#525]
### Interactsh version:

main | dev

### Current Behavior:

- interactsh client randomly exits with fatal error
```console
  [FTL] The correlation id was not found (probably evicted due to inactivity)
```
- https://github.com/projectdiscovery/interactsh/pull/524 temporarily fixes the issue by not exiting and only printing but the actual error is different . This is not reproducible in local machines but almost always visible in gh actions . probably something related to runners ?
- Ref: https://github.com/projectdiscovery/nuclei/actions/runs/4600751855/jobs/8127749422

### Expected Behavior:

- no error + no fatal exit

### Anything else:

- https://github.com/projectdiscovery/nuclei/issues/3507

**Comment by hakrishi** [comment]
Hi there, I received this issue this morning when using Nuclei Action. Do we have a rough idea when this issue will be resolved? Thanks

**Comment by tarunKoyalwar** [comment]
@hakrishi  , are you able to reproduce this with latest nuclei version https://github.com/projectdiscovery/nuclei/releases/tag/v2.9.2 .  partial fix is already included in latest release of nuclei and it will be fully resolved with https://github.com/projectdiscovery/interactsh/pull/531

**Comment by hakrishi** [comment]
Hey @tarunKoyalwar I ran an a scan and did not encounter this issue. I'll do some further testing over the next few weeks. Thanks!

**Comment by moisha207321** [comment]
the error is still thrown

**Comment by hakrishi** [comment]
After some further testing I am receiving this issue for all scans. (see screenshot attached)
![image](https://github.com/projectdiscovery/interactsh/assets/59293085/ac33762a-9860-4756-b1e4-12c48e58677f)

**Comment by rxerium** [comment]
Hi team, unfortunately I am still encountering this issue:
```
[ERR] The correlation id was not found (probably evicted due to inactivity): could not get correlation-id from cache
```

I am currently running v1.2.2 and my setup is through Docker:

```
sudo docker run -d projectdiscovery/interactsh-client:latest -token "XXX"
```

I am running Nuclei version 3.3.0.
